FROM python:3.12-slim AS build

ADD /giropops-senhas app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build /app app
COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

ENV PYTHONPATH=/usr/local/lib/python3.12/site-packages \
    FLASK_APP=/app/app.py

WORKDIR /app
EXPOSE 5001
ENTRYPOINT ["python", "-m", "flask", "run", "--host=0.0.0.0"]