services:
  giropops-senhas:
    image: sibelly/linuxtips-giropops-senhas:1.0
    ports: 
      - "5001:5001"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - giropops

networks:
  giropops:
    driver: bridge